<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_add.proto

namespace GPBMetadata\Plugin;

class HaiPluginAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99020a1b706c7567696e2f6861695f706c7567696e5f6164642e70726f" .
            "746f1206706c7567696e223a0a13486169506c7567696e41646452657175" .
            "65737412230a06706c7567696e18012001280b32132e636f72652e506c75" .
            "67696e50726f66696c6522160a14486169506c7567696e41646452657370" .
            "6f6e736532570a13486169506c7567696e4164645365727669636512400a" .
            "03616464121b2e706c7567696e2e486169506c7567696e41646452657175" .
            "6573741a1c2e706c7567696e2e486169506c7567696e416464526573706f" .
            "6e7365423d0a17636f6d2e616b6178696e2e70726f746f2e706c7567696e" .
            "4211486169506c7567696e41646450726f746fca020e4c6962726172795c" .
            "506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

