<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_update.proto

namespace GPBMetadata\Plugin;

class HaiPluginUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab020a1e706c7567696e2f6861695f706c7567696e5f7570646174652e" .
            "70726f746f120473697465223d0a16486169506c7567696e557064617465" .
            "5265717565737412230a06706c7567696e18012001280b32132e636f7265" .
            "2e506c7567696e50726f66696c6522190a17486169506c7567696e557064" .
            "617465526573706f6e7365325f0a16486169506c7567696e557064617465" .
            "5365727669636512450a06757064617465121c2e736974652e486169506c" .
            "7567696e557064617465526571756573741a1d2e736974652e486169506c" .
            "7567696e557064617465526573706f6e736542400a17636f6d2e616b6178" .
            "696e2e70726f746f2e706c7567696e4214486169506c7567696e55706461" .
            "746550726f746fca020e4c6962726172795c506c7567696e620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

