<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_list.proto

namespace GPBMetadata\Plugin;

class HaiPluginList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed020a1c706c7567696e2f6861695f706c7567696e5f6c6973742e7072" .
            "6f746f1206706c7567696e22620a14486169506c7567696e4c6973745265" .
            "717565737412130a0b706167655f6e756d62657218012001280512110a09" .
            "706167655f73697a6518022001280512220a067374617475731803200128" .
            "0e32122e636f72652e506c7567696e537461747573223c0a15486169506c" .
            "7567696e4c697374526573706f6e736512230a06706c7567696e18012003" .
            "280b32132e636f72652e506c7567696e50726f66696c65325b0a14486169" .
            "506c7567696e4c6973745365727669636512430a046c697374121c2e706c" .
            "7567696e2e486169506c7567696e4c697374526571756573741a1d2e706c" .
            "7567696e2e486169506c7567696e4c697374526573706f6e7365423e0a17" .
            "636f6d2e616b6178696e2e70726f746f2e706c7567696e4212486169506c" .
            "7567696e4c69737450726f746fca020e4c6962726172795c506c7567696e" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

