<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_profile.proto

namespace GPBMetadata\Plugin;

class HaiPluginProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6020a1f706c7567696e2f6861695f706c7567696e5f70726f66696c65" .
            "2e70726f746f120473697465222c0a17486169506c7567696e50726f6669" .
            "6c655265717565737412110a09706c7567696e5f6964180120012809223f" .
            "0a18486169506c7567696e50726f66696c65526573706f6e736512230a06" .
            "706c7567696e18012001280b32132e636f72652e506c7567696e50726f66" .
            "696c6532630a17486169506c7567696e50726f66696c6553657276696365" .
            "12480a0770726f66696c65121d2e736974652e486169506c7567696e5072" .
            "6f66696c65526571756573741a1e2e736974652e486169506c7567696e50" .
            "726f66696c65526573706f6e736542410a17636f6d2e616b6178696e2e70" .
            "726f746f2e706c7567696e4215486169506c7567696e50726f66696c6550" .
            "726f746fca020e4c6962726172795c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

