<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_search.proto

namespace GPBMetadata\Plugin;

class HaiUserSearch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad6020a1c706c7567696e2f6861695f757365725f7365617263682e7072" .
            "6f746f1206706c7567696e223f0a14486169557365725365617263685265" .
            "717565737412140a0c736974655f757365725f696418012001280912110a" .
            "09757365725f6e616d6518022001280922460a1548616955736572536561" .
            "726368526573706f6e7365122d0a0c757365725f70726f66696c65180120" .
            "03280b32172e636f72652e53696d706c655573657250726f66696c65325d" .
            "0a14486169557365725365617263685365727669636512450a0673656172" .
            "6368121c2e706c7567696e2e486169557365725365617263685265717565" .
            "73741a1d2e706c7567696e2e48616955736572536561726368526573706f" .
            "6e7365423e0a17636f6d2e616b6178696e2e70726f746f2e706c7567696e" .
            "42124861695573657253656172636850726f746fca020e4c696272617279" .
            "5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

